- type: remove
  path: /instance_groups/name=broker-registrar/jobs/name=broker-registrar/properties/cf

- type: replace
  path: /instance_groups/name=broker-registrar/jobs/name=broker-registrar/consumes?/cf-admin-user
  value:
    from: cf-admin-user
    deployment: cf

- type: remove
  path: /instance_groups/name=broker-deregistrar/jobs/name=broker-deregistrar/properties/cf

- type: replace
  path: /instance_groups/name=broker-deregistrar/jobs/name=broker-deregistrar/consumes?/cf-admin-user
  value:
    from: cf-admin-user
    deployment: cf
