---
- type: replace
  path: /releases/-
  value:
    name: broker-registrar
    version: 3.4.0
    url: https://github.com/cloudfoundry-community/broker-registrar-boshrelease/releases/download/v3.4.0/broker-registrar-3.4.0.tgz
    sha1: 76a66a16a8cb9261a207f6e9b6625fe71ef0f395

- type: replace
  path: /instance_groups/-
  value:
    name: broker-registrar
    instances: 1
    azs: [z1]
    lifecycle: errand
    vm_resources:
      ram: 1024
      cpu: 1
      ephemeral_disk_size: 10_000
    stemcell: default
    networks: [{name: default}]
    jobs:
    - name: broker-registrar
      release: broker-registrar
      consumes:
        servicebroker:
          from: kafka-service-broker
      properties:
        cf:
          api_url: ((cf-api-url))
          username: ((cf-admin-username))
          password: ((cf-admin-password))
          skip_ssl_validation: ((cf-skip-ssl-validation))

- type: replace
  path: /instance_groups/-
  value:
    name: broker-deregistrar
    instances: 1
    azs: [z1]
    lifecycle: errand
    vm_resources:
      ram: 1024
      cpu: 1
      ephemeral_disk_size: 10_000
    stemcell: default
    networks: [{name: default}]
    jobs:
    - name: broker-deregistrar
      release: broker-registrar
      consumes:
        servicebroker:
          from: kafka-service-broker
      properties:
        cf:
          api_url: ((cf-api-url))
          username: ((cf-admin-username))
          password: ((cf-admin-password))
          skip_ssl_validation: ((cf-skip-ssl-validation))
