---
name: kafka-service-broker

instance_groups:
- name: redis
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks: [{name: default}]
  jobs:
  - name: redis
    release: redis
    properties:
      password: ((redis-password))
- name: broker
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: kafka-service-broker
    release: kafka-service-broker
    properties: {}

variables:
- name: redis-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: true

releases:
- name: redis
  version: 13.0.0
  url: https://github.com/cloudfoundry-community/redis-boshrelease/releases/download/v13.0.0/redis-13.0.0.tgz
  sha1: 7cc104e398c7c7dc74841343e1a6b689927f7d99
- name: kafka-service-broker
  version: latest
