---
name: kafka-service-broker

instance_groups:
- name: broker-deploy
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-deploy
    release: kafka-service-broker
    properties:
      username: user
      password: ((broker-password))
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))
- name: broker-delete
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-delete
    release: kafka-service-broker
    properties:
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

- name: broker-registrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-registrar
    release: broker-registrar
    properties:
      servicebroker:
        url: http://dingo-kafka-broker.((cf-system-domain))
        name: dingo-kafka
        username: user
        password: ((broker-password))
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

- name: broker-deregistrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-deregistrar
    release: broker-registrar
    properties:
      servicebroker:
        name: dingo-kafka
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

variables:
- name: broker-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: true

releases:
- name: broker-registrar
  version: latest
  # version: 3.0.0
  # url: https://bosh.io/d/github.com/cloudfoundry-community/broker-registrar-boshrelease?v=3.0.0
  # sha1: d6486bfe6c76b612ab6e0c2d3e38376ad780f378
- name: kafka-service-broker
  version: latest
