---
name: kafka-service-broker

instance_groups:
- name: broker-deploy
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-deploy
    release: kafka-service-broker
    properties:
      username: user
      password: ((broker-password))
      redis:
        service_name: dingo-redis
        service_plan: ready

variables:
- name: broker-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: true

releases:
- name: kafka-service-broker
  version: latest
