---
processes:
- name: kafka-service-broker
  executable: /var/vcap/packages/kafka-service-broker/bin/broker
  args: []
  ephemeral_disk: true
  persistent_disk: false
  env:
    PORT: <%= p("port") %>
    <% zks = link('zookeeper'); zk_port = zks.p('client_port') %>
    ZOOKEEPER_PEERS: <%= zks.instances.map { |instance| "#{instance.address}:#{zk_port}" }.join(",") %>
  limits:
    memory: 128M
    open_files: 1024
