---
applications:
- name: <%= p("cf.appname") %>
  memory: <%= p("cf.appsize") %>
  instances: 1
  path: /var/vcap/packages/kafka-service-broker-src
  services: [ <%= p("cf.redis.service_instance_name") %> ]
  env:
    KAFKA_HOSTNAMES: <%= link('kafka').instances.first.address %>:<%= link('kafka').p("listen_port", 9092) %>
<% if_p("cf.routes") do |routes| -%>
  routes:
  <% routes.each do |route| -%>
  - route: <%= route %>
  <% end -%>
<% end %>
